version: '3.7'
services:

  mysql:
    image: mysql:5.6
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=message
    - MYSQL_USER=user
    - MYSQL_PASSWORD=user

    volumes:
    - ./mysql/init.d:/docker-entrypoint-initdb.d
    - dbdata:/var/lib/mysql

  api:
    build:
      context: .
    volumes:
    - .:/go/src/golang-public/api-ddd-model
    ports:
    - 8000:8000
    environment:
    - APP_ENV=local
    - APP_DIR=/go/src/golang-public/api-ddd-model
    links:
    - mysql:message.com

volumes:
  dbdata:
